# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74113da01fc86d2af89451b49fff21f16a71f287bfbf59eb8fd1aa9eb39090e5f4d03e140e4dd78a642aaac5ed799a17c805725704eb8a5ddd824e9c672787f2

test:
  secret_key_base: 844c0bf2408c5bb717b313d52bdadcef457fc9d4aa660cf1ed0d3277fe045a0fd2ec42fc6edfd4ff396c9fd2c97c4d9ae323911821126efa0a370a2c7df89a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
